# Generated by Django 6.0.3 on 2026-05-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_donneur_telephone'),
        ('donneur', '0001_initial'),
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseappel',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='hopital.demandeurgente'),
        ),
        migrations.AddField(
            model_name='reponseappel',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneur'),
        ),
        migrations.AlterUniqueTogether(
            name='reponseappel',
            unique_together={('demande', 'donneur')},
        ),
    ]
