# Generated by Django 6.0.2 on 2026-04-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='agrement',
        ),
    ]
