# Generated by Django 6.0.3 on 2026-05-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hopital_agrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneur',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
