# Generated by Django 6.0.3 on 2026-05-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donneur_adresse_donneur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
