# Generated by Django 6.0.2 on 2026-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_donneur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
