# Generated by Django 6.0.2 on 2026-05-09 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hopital_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
