# Generated by Django 6.0.2 on 2026-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hopital_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='est_valide',
            field=models.BooleanField(default=True),
        ),
    ]
