# Generated by Django 6.0.3 on 2026-05-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_donneur_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('quantite', models.IntegerField(help_text='Nombre de poches')),
                ('delai', models.DateField()),
                ('statut', models.CharField(default='Ouverte', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.hopital')),
            ],
        ),
    ]
