# Generated by Django 6.0.2 on 2026-05-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeurgente',
            name='statut',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
