# Generated by Django 6.0.2 on 2026-05-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hopital_est_valide'),
        ('hopital', '0002_alter_demandeurgente_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('groupes_cibles', models.CharField(blank=True, help_text='Ex: O+, A+, B- (séparés par des virgules)', max_length=100)),
                ('capacite_totale', models.IntegerField(default=100, help_text='Nombre total de donneurs possibles')),
                ('description', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='accounts.hopital')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.IntegerField(default=10)),
                ('date', models.DateField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='hopital.campagne')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('campagne', 'date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('confirme', 'Confirmé'), ('absent', 'Absent'), ('annule', 'Annulé')], default='inscrit', max_length=20)),
                ('present', models.BooleanField(default=False, help_text='Indicateur de présence le jour J')),
                ('notes', models.TextField(blank=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='hopital.campagne')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='hopital.creneau')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_campagne', to='accounts.donneur')),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('campagne', 'donneur')},
            },
        ),
    ]
